### ISSUE TITLE
Why is 405 Method Not Allowed always returned?

### ISSUE THREAD

**Issue by binarykitchen** [AveVlad/gulp-connect#170] opened 2016-03-13 03:41 UTC
This on POST requests.

```
> User-Agent: curl/7.43.0
> Accept: */*
> Content-Length: 167
> Content-Type: application/x-www-form-urlencoded
> 
* upload completely sent off: 167 out of 167 bytes
< HTTP/1.1 405 Method Not Allowed
< Allow: GET, HEAD, OPTIONS
< Content-Length: 0
< Date: Sun, 13 Mar 2016 02:46:59 GMT
< Connection: keep-alive
```

It is this code for reproduction:
https://github.com/binarykitchen/videomail-client/blob/master/Gulpfile.js#L104

**Comment by binarykitchen** [comment] 2016-03-13 04:47
Ah, I found the culprit. If remove the root option, then it works, no 405. Weird. Probably the connect.directory middleware is messing here with something else

**Comment by binarykitchen** [comment] 2016-03-13 04:53
Hmmm, serve-index causes this. See line https://github.com/expressjs/serve-index/blob/master/index.js#L102 ... uhhhh :(

**Comment by binarykitchen** [comment] 2016-03-13 04:55
a solution would be to rearrange the order. to run the custom middleware first before serve-index

**Comment by binarykitchen** [comment] 2016-03-13 05:00
@justinmchase ping

**Comment by binarykitchen** [comment] 2016-03-13 05:02
I think this commit broke it
https://github.com/AveVlad/gulp-connect/commit/1352e3d200e7dc8bba5e35226a85992a841f2356

Order of middleware is crucial. Please restore.

**Comment by justinmchase** [comment] 2016-03-16 21:55
I'm swamped right now but took a look at it and didn't see any obvious reason why the order of the middleware would be changed. Can you send a PR, or at least help me narrow down where the issue is happening? If I generally knew a fix I could probably crank it out in hours, sorry for delay.

**Comment by binarykitchen** [comment] 2016-03-18 00:39
@justinmchase here you go, it is very simple https://github.com/AveVlad/gulp-connect/pull/171

**Comment by justinmchase** [comment] 2016-03-18 22:20
Fixed in v3.1.1

**Closed by justinmchase** 2016-03-18 22:20 UTC
Labels: bug

**Comment by binarykitchen** [comment] 2016-03-19 01:22
great, the error is gone now, all works fine like before. thanks for quick reaction

**Comment by binarykitchen** [comment] 2016-03-19 01:24
ps: @justinmchase can you please look at https://github.com/AveVlad/gulp-connect/issues/140?
