### ISSUE TITLE
Ignoring index.html

### ISSUE THREAD

**Issue by fegemo** [AveVlad/gulp-connect#163] opened 2016-02-25 23:02 UTC
Hi. I've just updated to v3.0.0 and I noticed that it seems that connect started ignoring index.html inside folders, showing the directory listing instead of the html file.

Is this an intended change?

Thanks for the plugin!!

**Comment by SuneBear** [comment] 2016-02-26 05:52
+1, I had the same problem : (

**Comment by erkobridee** [comment] 2016-02-27 02:15
+1, same problem here with v3.0.0

**Comment by RyanWarner** [comment] 2016-02-27 14:20
+1 same problem here

**Comment by EHLOVader** [comment] 2016-02-28 02:45
Looks like https://github.com/AveVlad/gulp-connect/pull/160 is the cause of the problems. Lots of changes including the fallback option which defaults to undefined in there.

I tried setting the fallback to `index.html` but then I got stranger errors about the file not being found.

```
Error: ENOENT: no such file or directory, open 'index.html'
```

**Comment by red2678** [comment] 2016-02-28 23:41
+1 Same here

**Comment by muzuiget** [comment] 2016-02-29 02:57
Same here, even setting `fallback` option, still not work.

**Comment by syed-haroon** [comment] 2016-02-29 18:13
+1  I have updated to  v3.0.1 but still have the same problem.

**Comment by stevenorell** [comment] 2016-03-01 03:43
+1, same issue. Running 3.1.0, I just get a directory listing, even with the fallback set to the path to index.html. This is my task:

```
gulp.task('connect', function(){
  connect.server({
    fallback: './src/index.html',
    root: './src'
  });
});
```

**Comment by mafrost** [comment] 2016-03-01 07:29
+1 Also having this problem

**Comment by bagwaa** [comment] 2016-03-01 10:19
+1 same problem

**Comment by alessiodionisi** [comment] 2016-03-02 09:35
+1 same problem

**Comment by britztopher** [comment] 2016-03-02 18:56
+1 same problem as well

**Comment by simon-thorpe** [comment] 2016-03-03 21:52
+1 here

**Comment by jornbakhuys** [comment] 2016-03-04 15:51
+1 same problem

**Comment by OutThisLife** [comment] 2016-03-04 20:25
+1

**Comment by adrianchung** [comment] 2016-03-04 22:17
+1

**Comment by lusarz** [comment] 2016-03-08 13:21
+1

**Comment by nerdybeast** [comment] 2016-03-08 16:36
+1

**Comment by musamanyama** [comment] 2016-03-10 14:09
Thank you euwest, hope this gets merged quickly :+1:

**Comment by blinkcat** [comment] 2016-03-11 07:16
+1

**Comment by michaelryancaputo** [comment] 2016-03-11 17:20
@blinkcat Github has reactions now :dancer:

**Comment by enlore** [comment] 2016-03-16 20:14
+1

**Comment by samueledirito** [comment] 2016-03-16 21:24
+1

**Comment by airwin** [comment] 2016-03-17 03:59
+1024 :(

**Comment by red2678** [comment] 2016-03-17 13:27
Problem solved! http://browsersync.io

**Comment by fegemo** [comment] 2016-03-17 16:18
@red2678, I tried it as a replacement for gulp-connect and dropped it.

For my scenario, which is to use gulp-connect just to have livereloading during dev, using browsersync is like killing an ant with a bazooka - besides, it introduces some overhead, which hurts performance.

Last, it is not a nice thing to advertise other solutions in such a way when we are in open source world ;)

**Comment by jwhitmarsh** [comment] 2016-03-18 16:12
+1+1

**Comment by s3bubble** [comment] 2016-03-18 21:47
+++1

**Closed** 2016-03-20 14:57 UTC

**Comment by 59naga** [comment] 2016-06-15 13:16
my solved case:
```js
  connect.server({
    livereload: {
      include: [/^(?!.*index\.html)*$/]
    }
  })
```

**Comment by 59naga** [comment] 2016-06-15 13:35
solved my case(required remove cache):
```js
  connect.server({
    livereload: {
      include: [/^\/.+?$/]
    }
  })
```

**Comment by vangorra** [comment] 2017-05-13 12:02
I found setting the path to fallback to an absolute path works great.

``` javascript
  connect.server({
    root: path.resolve(path.join(__dirname, 'dist/app')),
    livereload: false,
    host: '0.0.0.0',
    port: 8000,
    fallback: path.resolve('./dist/app/index.html')
  });
```

**Comment by fygethub** [comment] 2018-02-07 02:33
@vangorra  Thanks,It works when I replace the fallback to an absolute path
